// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnoxdbvpheowgugeyyfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZub3hkYnZwaGVvd2d1Z2V5eWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzUxMTksImV4cCI6MjA2MTM1MTExOX0.uPjUDPr3PaTyWgjBSUrhXIrOHbw1DFVWyaU6q02YowM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);